name: Update domain lists for SmartDNS

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare domain-set directory
        run: mkdir -p domain-set

      - name: Download and process domain lists
        run: |
          curl -sSL https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt  >> domain-set/direct-list.txt
          curl -sSL https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt    >> domain-set/direct-list.txt
          curl -sSL https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/google-cn.txt   >> domain-set/direct-list.txt
          sed -i '/^regexp:/d; s/full://g' domain-set/direct-list.txt
          sort -u domain-set/direct-list.txt -o domain-set/direct-list.txt

          curl -sSL https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt >> domain-set/proxy-list.txt
          sed -i '/^regexp:/d; s/full://g' domain-set/proxy-list.txt
          sort -u domain-set/proxy-list.txt -o domain-set/proxy-list.txt

          curl -sSL https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt >> domain-set/reject-list.txt
          sed -i '/^regexp:/d; s/full://g' domain-set/reject-list.txt
          sort -u domain-set/reject-list.txt -o domain-set/reject-list.txt

      - name: Archive domain lists
        run: zip -r smartdns-domain-lists.zip domain-set

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: domain-lists-${{ steps.date.outputs.date }}
          name: Domain Lists ${{ steps.date.outputs.date }}
          body: 自动更新域名清单，包含 direct / proxy / reject
          files: smartdns-domain-lists.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old Releases (保留最近 7 个)
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 7
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
